services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=shop
      - TZ=Europe/Sarajevo
    networks:
      - net
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "80:80"
    networks:
      - net
    environment:
      - PMA_HOST=mysql
  back:
    build: ./back
    container_name: backend
    ports:
      - 5000:5000
    volumes:
      - ./back:/src
    networks:
      - net
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=secret
      - MYSQL_DB=shop
  front:
    build: ./front
    container_name: frontend
    volumes:
      - ./front:/src
      - node_modules:/src/node_modules
    ports:
      - 3000:3000
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
volumes:
  db:
  node_modules:
networks:
  net:
